### ISSUE TITLE
How to use the paramaters

### ISSUE THREAD

**Issue by phenix1983** [madaiqian/moving-object-detection#1]
input a sequence , the moving object cannot be detected, how to adjust  epipolar constraint parameters.
the sequence is like this, the camera installed on back rear, some cars parked and a person walked pass in the background .

**Comment by madaiqian** [comment]
"double limit_dis_epi =2; //距离极线的距离 "    this threshold controls the judgement of moving objects, if u want to detect slow-moving objects, you can reduce this threhold
